const provinces = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Kepulauan Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "DKI Jakarta",
  "Banten",
  "Jawa Barat",
  "Jawa Tengah",
  "Daerah Istimewa Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Sulawesi Tengah",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Gorontalo",
  "Sulawesi Barat",
  "Maluku",
  "Maluku Utara",
  "Papua",
  "Papua Barat",
  "Papua Selatan",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Barat Daya",
];

const citiesByProvince = {
  Aceh: [
    "Kab. Aceh Besar",
    "Kab. Bireuen",
    "Kota Banda Aceh",
    "Kota Lhokseumawe",
  ],
  "Sumatera Utara": [
    "Kab. Deli Serdang",
    "Kab. Langkat",
    "Kota Medan",
    "Kota Binjai",
  ],
  "Sumatera Barat": [
    "Kab. Agam",
    "Kab. Lima Puluh Kota",
    "Kota Padang",
    "Kota Bukittinggi",
  ],
  Riau: ["Kab. Kampar", "Kab. Rokan Hulu", "Kota Pekanbaru", "Kota Dumai"],
  "Kepulauan Riau": [
    "Kab. Bintan",
    "Kab. Karimun",
    "Kota Batam",
    "Kota Tanjungpinang",
  ],
  Jambi: ["Kab. Batanghari", "Kab. Muaro Jambi", "Kota Jambi"],
  "Sumatera Selatan": [
    "Kab. Banyuasin",
    "Kab. Ogan Ilir",
    "Kota Palembang",
    "Kota Prabumulih",
  ],
  "Kepulauan Bangka Belitung": [
    "Kab. Bangka",
    "Kab. Belitung",
    "Kota Pangkalpinang",
  ],
  Bengkulu: ["Kab. Bengkulu Selatan", "Kab. Bengkulu Utara", "Kota Bengkulu"],
  Lampung: [
    "Kab. Lampung Selatan",
    "Kab. Lampung Tengah",
    "Kota Bandar Lampung",
    "Kota Metro",
  ],
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Utara",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Timur",
  ],
  Banten: ["Kab. Tangerang", "Kab. Serang", "Kota Tangerang", "Kota Serang"],
  "Jawa Barat": [
    "Kab. Bandung",
    "Kab. Bogor",
    "Kab. Bekasi",
    "Kota Bandung",
    "Kota Bekasi",
  ],
  "Jawa Tengah": [
    "Kab. Semarang",
    "Kab. Surakarta",
    "Kab. Tegal",
    "Kota Semarang",
    "Kota Surakarta",
  ],
  "Daerah Istimewa Yogyakarta": [
    "Kab. Sleman",
    "Kab. Bantul",
    "Kota Yogyakarta",
  ],
  "Jawa Timur": [
    "Kab. Bangkalan",
    "Kab. Banyuwangi",
    "Kab. Blitar",
    "Kab. Jember",
    "Kab. Jombang",
    "Kab. Kediri",
    "Kab. Lamongan",
    "Kab. Lumajang",
    "Kab. Madiun",
    "Kab. Magetan",
    "Kab. Malang",
    "Kab. Mojokerto",
    "Kab. Pacitan",
    "Kab. Pasuruan",
    "Kab. Sidoarjo",
    "Kota Malang",
    "Kota Surabaya",
  ],
  Bali: ["Kab. Badung", "Kab. Gianyar", "Kota Denpasar"],
  "Nusa Tenggara Barat": [
    "Kab. Lombok Barat",
    "Kab. Lombok Tengah",
    "Kota Mataram",
  ],
  "Nusa Tenggara Timur": ["Kab. Kupang", "Kab. Manggarai", "Kota Kupang"],
  "Kalimantan Barat": [
    "Kab. Pontianak",
    "Kab. Sambas",
    "Kab. Kapuas Hulu",
    "Kota Pontianak",
  ],
  "Kalimantan Tengah": [
    "Kab. Kotawaringin Barat",
    "Kab. Kapuas",
    "Kota Palangka Raya",
  ],
  "Kalimantan Selatan": [
    "Kab. Banjar",
    "Kab. Barito Kuala",
    "Kota Banjarmasin",
  ],
  "Kalimantan Timur": [
    "Kab. Kutai Kartanegara",
    "Kab. Berau",
    "Kota Samarinda",
    "Kota Balikpapan",
  ],
  "Kalimantan Utara": ["Kab. Bulungan", "Kab. Nunukan", "Kota Tarakan"],
  "Sulawesi Utara": [
    "Kab. Minahasa",
    "Kab. Bolaang Mongondow",
    "Kota Manado",
    "Kota Bitung",
  ],
  "Sulawesi Tengah": ["Kab. Donggala", "Kab. Poso", "Kota Palu"],
  "Sulawesi Selatan": ["Kab. Gowa", "Kab. Bone", "Kota Makassar"],
  "Sulawesi Tenggara": ["Kab. Konawe", "Kab. Muna", "Kota Kendari"],
  Gorontalo: ["Kab. Gorontalo", "Kab. Boalemo", "Kota Gorontalo"],
  "Sulawesi Barat": ["Kab. Mamuju", "Kab. Polewali Mandar"],
  Maluku: ["Kab. Maluku Tengah", "Kab. Seram Bagian Barat", "Kota Ambon"],
  "Maluku Utara": [
    "Kab. Halmahera Barat",
    "Kab. Halmahera Selatan",
    "Kota Ternate",
    "Kota Tidore Kepulauan",
  ],
  Papua: ["Kab. Jayapura", "Kab. Mimika", "Kota Jayapura"],
  "Papua Barat": ["Kab. Manokwari", "Kab. Fakfak", "Kota Sorong"],
  "Papua Selatan": ["Kab. Merauke", "Kab. Mappi"],
  "Papua Tengah": ["Kab. Nabire", "Kab. Paniai"],
  "Papua Pegunungan": ["Kab. Jayawijaya", "Kab. Yahukimo"],
  "Papua Barat Daya": ["Kab. Sorong", "Kab. Raja Ampat", "Kota Sorong"],
};

export { provinces, citiesByProvince };
