export const CSOrderStatusEnum = {
  WAITING_CONFIRMATION_SHIPPER: "WAITING_CONFIRMATION_SHIPPER",
  CONFIRMED: "CONFIRMED",
  NEED_ASSIGN_FLEET: "NEED_ASSIGN_FLEET",
  SCHEDULED_FLEET: "SCHEDULED_FLEET",
  NEED_CONFIRMATION_READY: "NEED_CONFIRMATION_READY",
  NEED_CONFIRMATION_CHANGES: "NEED_CONFIRMATION_CHANGES",
  LOADING: "LOADING",
  UNLOADING: "UNLOADING",
  PREPARE_DOCUMENT: "PREPARE_DOCUMENT",
  DOCUMENT_DELIVERY: "DOCUMENT_DELIVERY",
  COMPLETED: "COMPLETED",
};

export const CSOrderStatusTitle = {
  WAITING_CONFIRMATION_SHIPPER: "Menunggu Konfirmasi Shipper",
  CONFIRMED: "statusPesananTerkonfirmasi",
  NEED_ASSIGN_FLEET: "Perlu Assign Armada",
  SCHEDULED_FLEET: "statusArmadaDijadwalkan",
  NEED_CONFIRMATION_READY: "Perlu Konfirmasi Siap",
  NEED_CONFIRMATION_CHANGES: "Perlu Respon Perubahan",
  LOADING: "statusProsesMuat",
  UNLOADING: "statusProsesBongkar",
  PREPARE_DOCUMENT: "statusDokumenDisiapkan",
  DOCUMENT_DELIVERY: "statusPengirimanDokumen",
  COMPLETED: "statusSelesai",
};
